### ISSUE TITLE
Error: Unexpected key "rotate" within field "..."

### ISSUE THREAD

**Issue by nouun** [ergogen/ergogen#72]
While attempting to build my layout, I came across an error and decided to try build the example Absolem and noticed that this also has the same error.

```
 .../ergogen > node src/cli.js test.yaml output-test
Ergogen v4.0.0-develop CLI

Interpreting format: YAML
Preprocessing input...
Calculating variables...
Parsing points...
Error: Unexpected key "rotate" within field "points.zones.matrix.columns.ring"!
```

**Comment by mrzealot** [comment]
Hey! This is because you're using an officially unreleased (and undocumented) version, as indicated by the console output `Ergogen v4.0.0-develop`. Check out stuff on the `master` branch and things should work smoother :ok_hand: Also, if you have further questions, feel free to swing by the Discord for a bit more direct line of communication...
